### ISSUE TITLE
Link to the stylesheet

### ISSUE THREAD

**Issue by nevanscott** [raphamontenegro/uxui-codeweek#1]
https://github.com/raphamontenegro/uxui-codeweek/blob/234600e6469017779c97a5c9ee6fd4f0b7551cf4/boiler-plates/index.html#L8

I think this would make more sense if it worked out of the box. Then you can intentionally change it if you want to link to a different CSS file.

**Comment by nevanscott** [comment]
Since there's a `main.css` file, seems like this should just read:

```html
<link rel="stylesheet" href="main.css">
```

**Comment by raphamontenegro** [comment]
Fixed!
